# Prometheus configuration for Lighthouse Bridge monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'lighthouse-development'
    replica: 'prometheus-01'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      # - alertmanager:9093

# Rule files
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics
    
  # Lighthouse Bridge main metrics
  - job_name: 'lighthouse-bridge'
    static_configs:
      - targets: ['lighthouse-bridge:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: false
    honor_timestamps: true
    
    # Custom metric relabeling
    metric_relabel_configs:
      # Add service label
      - source_labels: [__name__]
        target_label: service
        replacement: lighthouse-bridge
        
      # Normalize component metrics
      - source_labels: [__name__]
        regex: 'lighthouse_bridge_(.+)'
        target_label: component
        replacement: '${1}'
    
  # Bridge health endpoints
  - job_name: 'lighthouse-bridge-health'
    static_configs:
      - targets: ['lighthouse-bridge:8765']
    scrape_interval: 30s
    metrics_path: /health/metrics
    scrape_timeout: 5s
    
  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics
    
  # PostgreSQL monitoring (if exporter available)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    honor_timestamps: true
    
  # Container metrics (cAdvisor if available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    honor_labels: true
    
  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    
# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB
    
# Remote write (for production environments)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"